apiVersion: v1
kind: Service
metadata:
  name: python-ml-service
  namespace: marketguard
  annotations:
    argocd.argoproj.io/sync-wave: "1"    # ← deploy second
spec:
  selector:
    app: python-ml-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP