apiVersion: v1
kind: Service
metadata:
  name: python-ml-service
  namespace: marketguard
spec:
  selector:
    app: python-ml-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP