apiVersion: apps/v1
kind: Deployment
metadata:
  name: validation-prediction-service
  namespace: marketguard
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 0
  selector:
    matchLabels:
      app: validation-prediction-service
  template:
    metadata:
      labels:
        app: validation-prediction-service
    spec:
      containers:
        - name: validation-prediction-service
          image: ghcr.io/sivejozi/validation-prediction-service:cf50041f1cdc53f4fd6203d1805051073be81c69
          ports:
            - containerPort: 8081
          env:
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE
              value: http://discovery-service.marketguard.svc.cluster.local:8061/eureka/
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: validation-prediction-service-secrets
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: validation-prediction-service-secrets
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: validation-prediction-service-secrets
                  key: SPRING_DATASOURCE_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: validation-prediction-service-secrets
                  key: JWT_SECRET
            - name: JWT_EXPIRATION
              value: "86400000"
            - name: JASYPT_ENCRYPTOR_PASSWORD
              value: cp-pass
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 5
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 20
            failureThreshold: 3