apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: marketguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: ghcr.io/sivejozi/gateway-service:40aea89d3e84b9252e263b9d2925ebc0f1ad25e6
          ports:
            - containerPort: 8082
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /
              port: 8061
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 20