apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: marketguard
spec:
  selector:
    app: gateway-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP