apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: validation-prediction-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sivejozi/market-data-system-gitops.git
    targetRevision: HEAD
    path: validation-prediction-service
  destination:
    server: https://kubernetes.default.svc
    namespace: marketguard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true